const CONSTANTS = {
  post: {
    FETCH_POSTS: "FETCH_POSTS",
    CREATE_POSTS: "CREATE_POSTS",
    UPDATE_POST_SPECIFIC: "UPDATE_POST_SPECIFIC",
    DELETE_POSTS: "DELETE_POSTS",
    LIKE_POSTS: "LIKE_POSTS",
  },
  auth: {
    AUTH: "AUTH",
    LOGOUT: "LOGOUT",
  },
};
export default CONSTANTS;
